repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args:
        - "-l 128"

- repo: local
  hooks:
    - id: cleartoken
      name: cleartoken
      entry: python pre-commit-cleartoken.py
      language: python
